stages:
  data_prep:
    cmd: python -m prepare_data
    wdir: src
    deps:
    - prepare_data.py
    - ../data/raw/credit_risk_dataset.csv
    outs:
    - ../data/processed/credit_risk_prepared.csv
  train:
    cmd: python -m   train
    wdir: src
    deps:
    -  train.py
    -  ../data/processed/credit_risk_prepared.csv
    outs:
    - ../models/model.pkl
